[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan cache:clear",
  "php artisan config:cache",
  "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"